import { useEffect, useMemo, useState } from "react";
import { AlertCircle, Database, Image, ShieldAlert, Video } from "lucide-react";
import { getAnalyses, getHealth, getStats, predictImage, predictVideo } from "./api.js";
import HealthBadge from "./components/HealthBadge.jsx";
import ResultCard from "./components/ResultCard.jsx";
import UploadBox from "./components/UploadBox.jsx";

const DISCLAIMER = "Research prototype only. Training-label order is missing, so outputs have no verified real-world meaning and must never be used as evidence or for law-enforcement, safety, or emergency decisions.";
const DEMOS = [
  { id:"subway", title:"Subway robbery", file:"/demos/subway-robbery.webm", filename:"demo-subway-robbery.webm", detail:"Reported theft and assault // 6 seconds", severity:"warning", response:"Review now", source:"https://commons.wikimedia.org/wiki/File:NYPD_Wanted_-_Robbery_(Manhattan).webm" },
  { id:"street", title:"Armed street robbery", file:"/demos/street-robbery.webm", filename:"demo-street-robbery.webm", detail:"Reported weapon assault // 6 seconds", severity:"danger", response:"Immediate alert", source:"https://commons.wikimedia.org/wiki/File:Robbery_75_Precinct_-_6-23-12.webm" },
  { id:"store", title:"Armed store robbery", file:"/demos/store-robbery.webm", filename:"demo-store-robbery.webm", detail:"Reported gunpoint robbery // 12 seconds", severity:"danger", response:"Immediate alert", source:"https://commons.wikimedia.org/wiki/File:81_Precinct_Robbery_-_7-18-12.webm" },
  { id:"carwash", title:"Car-wash robbery", file:"/demos/surveillance-robbery.webm", filename:"demo-carwash-robbery.webm", detail:"Reported armed robbery // 38 seconds", severity:"danger", response:"Immediate alert", source:"https://commons.wikimedia.org/wiki/File:Robbery_Suspects_Caught_on_Surveillance_Camera.webm" },
];

export default function App() {
  const [health,setHealth]=useState(null),[healthLoading,setHealthLoading]=useState(true),[imageFile,setImageFile]=useState(null),[imageResult,setImageResult]=useState(null),[videoFile,setVideoFile]=useState(null),[videoResult,setVideoResult]=useState(null),[selectedDemo,setSelectedDemo]=useState(null),[playbackTime,setPlaybackTime]=useState(0),[loading,setLoading]=useState(false),[videoLoading,setVideoLoading]=useState(false),[error,setError]=useState(""),[analyses,setAnalyses]=useState([]),[stats,setStats]=useState({total:0,by_kind:{}}),[sampleEvery,setSampleEvery]=useState(30);
  const previewUrl=useMemo(()=>imageFile?URL.createObjectURL(imageFile):"",[imageFile]);
  const videoPreviewUrl=useMemo(()=>videoFile?URL.createObjectURL(videoFile):"",[videoFile]);
  useEffect(()=>{getHealth().then(setHealth).catch(err=>setHealth({status:"error",message:err.message})).finally(()=>setHealthLoading(false));},[]);
  async function refreshHistory(){const [historyData,statsData]=await Promise.all([getAnalyses(),getStats()]);setAnalyses(historyData.analyses||[]);setStats(statsData);}
  useEffect(()=>{refreshHistory().catch(()=>null);},[]);
  useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl);},[previewUrl]);
  useEffect(()=>()=>{if(videoPreviewUrl)URL.revokeObjectURL(videoPreviewUrl);},[videoPreviewUrl]);
  async function handleImage(file){setImageFile(file);setImageResult(null);setError("");setLoading(true);try{setImageResult(await predictImage(file));await refreshHistory().catch(()=>null);}catch(err){setError(err.message);}finally{setLoading(false);}}
  async function handleVideo(file){setSelectedDemo(null);setVideoFile(file);setVideoResult(null);setError("");setVideoLoading(true);try{setVideoResult(await predictVideo(file,sampleEvery));await refreshHistory().catch(()=>null);}catch(err){setError(err.message);}finally{setVideoLoading(false);}}
  async function runDemo(demo){setSelectedDemo(demo);setError("");setVideoLoading(true);try{const response=await fetch(demo.file);if(!response.ok)throw new Error("Demo file could not be loaded.");const blob=await response.blob();const file=new File([blob],demo.filename,{type:"video/webm"});setVideoFile(file);setVideoResult(null);setVideoResult(await predictVideo(file,sampleEvery));await refreshHistory().catch(()=>null);document.getElementById("video-analysis")?.scrollIntoView({behavior:"smooth",block:"start"});}catch(err){setError(err.message);}finally{setVideoLoading(false);}}
  return <main className="console-shell"><div className="console-wrap">
    <header className="masthead"><div><p className="eyebrow">Cyber Police // Visual Forensics</p><h1 className="hero-title">Event Analysis Console</h1><p className="hero-copy">Inspect visual model output, compare probability signals, and review analysis telemetry from one controlled workspace.</p></div><HealthBadge health={health} loading={healthLoading}/></header>
    <div className="warning-strip"><AlertCircle className="h-5 w-5 shrink-0"/><p>{DISCLAIMER}</p></div>
    <section className="how-it-works" aria-label="How to use this prototype"><div><strong>1</strong><span><b>Choose footage</b><small>Use a demo or your own video.</small></span></div><div><strong>2</strong><span><b>Wait for the scan</b><small>The existing model checks sampled frames.</small></span></div><div><strong>3</strong><span><b>Review the warning</b><small>Replay with a clear status and timeline.</small></span></div></section>
    {error&&<div className="error-strip"><AlertCircle className="h-5 w-5 shrink-0"/><p>{error}</p></div>}
    <section className="metric-grid" aria-label="Analysis overview"><Metric label="Saved analyses" value={stats.total||0} icon={Database}/><Metric label="Image records" value={stats.by_kind?.image||0} icon={Image}/><Metric label="Video records" value={stats.by_kind?.video||0} icon={Video}/></section>
    <section className="panel"><div className="panel-head"><div><p className="module-id">Quick start // Real CCTV samples</p><h2>Try a Video</h2><p className="muted mt-2 text-sm">Preview a clip, then select “Analyze video.” The colored badge is a human-provided demo annotation—not a model prediction.</p></div></div><div className="severity-guide"><span className="clear">Routine activity</span><span className="warning">Weapon shown → review</span><span className="danger">Attack in progress → alert</span></div><div className="demo-grid">{DEMOS.map(demo=><article className="demo-card" key={demo.id}><div className="video-wrap"><video src={demo.file} controls muted playsInline preload="metadata" aria-label={`${demo.title} preview`}/><span className={`severity-badge ${demo.severity}`}>{demo.response}</span></div><div className="demo-copy"><h3>{demo.title}</h3><p className="muted">{demo.detail}</p><div className="demo-actions"><button className="action-button" disabled={videoLoading} onClick={()=>runDemo(demo)}>{videoLoading?"Analyzing…":"Analyze video"}</button><a href={demo.source} target="_blank" rel="noreferrer">View source</a></div></div></article>)}</div><p className="demo-note">Content note: real, non-graphic surveillance footage of reported crimes. Videos do not autoplay. Sources and public-domain claims are linked on every card.</p></section>
    <section className="grid-two"><UploadBox title="Evidence image input" description="Load one local frame to inspect anonymous class probabilities." accept="image/*" previewUrl={previewUrl} fileName={imageFile?.name} loading={loading} onFile={handleImage}/><ResultCard result={imageResult}/></section>
    <section className="grid-two" id="video-analysis"><UploadBox title="Video signal sampler" description="Sample frames from a local video and summarize model output over time." accept="video/*" fileName={videoFile?.name} loading={videoLoading} onFile={handleVideo} mode="video"/>
      <RiskMonitor result={videoResult} videoUrl={videoPreviewUrl} demo={selectedDemo} playbackTime={playbackTime} onTime={setPlaybackTime} sampleEvery={sampleEvery} onSampleEvery={setSampleEvery}/>
    </section>
    <section className="panel"><div className="panel-head"><div><p className="module-id">Module 05 // Archive</p><h2>Recent Analyses</h2><p className="muted mt-2 text-sm">MongoDB stores metadata and outputs only. Uploaded media is discarded after processing.</p></div><button className="action-button" onClick={()=>refreshHistory().catch(err=>setError(err.message))}>Refresh feed</button></div>{analyses.length?<div className="data-table">{analyses.map(a=><div key={a.id} className="archive-row"><span className="archive-kind">{a.kind}</span><div className="truncate"><strong>{a.filename}</strong><div className="muted truncate">{a.predicted_class||`${a.sampled_frames||0} sampled frames`}</div></div><time className="muted" dateTime={a.created_at}>{new Date(a.created_at).toLocaleString()}</time></div>)}</div>:<p className="muted text-sm">No analyses saved. Load an image or video to initialize the feed.</p>}</section>
  </div></main>;
}
function Metric({label,value,icon:Icon}){return <div className="metric">{Icon&&<Icon className="metric-icon"/>}<p className="metric-label">{label}</p><p className="metric-value">{value}</p></div>}

const DEMO_RISK={class_0:18,class_1:58,class_2:92};
function RiskMonitor({result,videoUrl,demo,playbackTime,onTime,sampleEvery,onSampleEvery}){
 const frame=result?.frame_predictions?.reduce((closest,item)=>Math.abs(item.timestamp_seconds-playbackTime)<Math.abs(closest.timestamp_seconds-playbackTime)?item:closest,result.frame_predictions[0]);
 const risk=frame?DEMO_RISK[frame.predicted_class]??Math.round(frame.confidence*100):0;
 const level=demo?.severity||(risk>=75?"danger":risk>=40?"warning":"clear");
 const shownRisk=demo?(demo.severity==="danger"?90:60):risk;
 return <section className={`panel risk-monitor ${level}`}><p className="module-id">Result // Monitored playback</p><h2>Risk Warning</h2>{result&&videoUrl?<div className="mt-5">{demo&&<p className="annotation-note">Demo annotation: <strong>{demo.detail}</strong></p>}<div className={`live-alert ${level}`}><ShieldAlert/><div><span>{level==="danger"?"Immediate attention":level==="warning"?"Review required":"No elevated signal"}</span><small>{demo?"Known demo scenario":"Unverified prototype mapping"} // {playbackTime.toFixed(1)} seconds</small></div><strong>{shownRisk}%</strong></div><video className="monitor-video" src={videoUrl} controls playsInline onTimeUpdate={e=>onTime(e.currentTarget.currentTime)}/><div className="risk-track"><div className="risk-level" style={{width:`${shownRisk}%`}}/></div><div className="risk-labels"><span>LOW</span><span>REVIEW</span><span>ALERT</span></div><details className="model-details"><summary>What did the original model return?</summary><p>Nearest sample: <strong>{frame?.predicted_class}</strong> at {Math.round((frame?.confidence||0)*100)}% confidence. Its class meaning is unknown.</p></details><p className="warning-strip mt-4">This duplicate demonstrates warning UX. Demo severity comes from the documented incident context; custom uploads still use an unverified class mapping.</p></div>:<p className="muted mt-3 text-sm leading-6">Choose a sample above or upload a video. After scanning, the warning and monitored replay will appear here.</p>}<label className="muted mt-5 block text-sm">Scan detail // every {sampleEvery} frames<input className="range-control mt-3" type="range" min="5" max="120" step="5" value={sampleEvery} onChange={e=>onSampleEvery(Number(e.target.value))}/></label></section>;
}
