import { useEffect, useMemo, useRef, useState } from "react";
import { AlertCircle, Database, Image, ShieldAlert, Video } from "lucide-react";
import { getAnalyses, getHealth, getStats, predictImage } from "./api.js";
import HealthBadge from "./components/HealthBadge.jsx";
import ResultCard from "./components/ResultCard.jsx";
import UploadBox from "./components/UploadBox.jsx";

const DISCLAIMER = "Research prototype only. Training-label order is missing, so outputs have no verified real-world meaning and must never be used as evidence or for law-enforcement, safety, or emergency decisions.";
const DEMOS = [
  { id:"subway", title:"Subway robbery", file:"/demos/subway-robbery.webm", filename:"demo-subway-robbery.webm", detail:"Reported theft and assault // 6 seconds", severity:"warning", response:"Review now", source:"https://commons.wikimedia.org/wiki/File:NYPD_Wanted_-_Robbery_(Manhattan).webm" },
  { id:"street", title:"Armed street robbery", file:"/demos/street-robbery.webm", filename:"demo-street-robbery.webm", detail:"Reported weapon assault // 6 seconds", severity:"danger", response:"Immediate alert", source:"https://commons.wikimedia.org/wiki/File:Robbery_75_Precinct_-_6-23-12.webm" },
  { id:"store", title:"Armed store robbery", file:"/demos/store-robbery.webm", filename:"demo-store-robbery.webm", detail:"Reported gunpoint robbery // 12 seconds", severity:"danger", response:"Immediate alert", source:"https://commons.wikimedia.org/wiki/File:81_Precinct_Robbery_-_7-18-12.webm" },
  { id:"carwash", title:"Car-wash robbery", file:"/demos/surveillance-robbery.webm", filename:"demo-carwash-robbery.webm", detail:"Reported armed robbery // 38 seconds", severity:"danger", response:"Immediate alert", source:"https://commons.wikimedia.org/wiki/File:Robbery_Suspects_Caught_on_Surveillance_Camera.webm" },
];

export default function App() {
  const [health,setHealth]=useState(null),[healthLoading,setHealthLoading]=useState(true),[imageFile,setImageFile]=useState(null),[imageResult,setImageResult]=useState(null),[videoFile,setVideoFile]=useState(null),[selectedDemo,setSelectedDemo]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[analyses,setAnalyses]=useState([]),[stats,setStats]=useState({total:0,by_kind:{}});
  const previewUrl=useMemo(()=>imageFile?URL.createObjectURL(imageFile):"",[imageFile]);
  const videoPreviewUrl=useMemo(()=>videoFile?URL.createObjectURL(videoFile):"",[videoFile]);
  useEffect(()=>{getHealth().then(setHealth).catch(err=>setHealth({status:"error",message:err.message})).finally(()=>setHealthLoading(false));},[]);
  async function refreshHistory(){const [historyData,statsData]=await Promise.all([getAnalyses(),getStats()]);setAnalyses(historyData.analyses||[]);setStats(statsData);}
  useEffect(()=>{refreshHistory().catch(()=>null);},[]);
  useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl);},[previewUrl]);
  useEffect(()=>()=>{if(videoPreviewUrl)URL.revokeObjectURL(videoPreviewUrl);},[videoPreviewUrl]);
  async function handleImage(file){setImageFile(file);setImageResult(null);setError("");setLoading(true);try{setImageResult(await predictImage(file));await refreshHistory().catch(()=>null);}catch(err){setError(err.message);}finally{setLoading(false);}}
  function handleVideo(file){setSelectedDemo(null);setVideoFile(file);setError("");document.getElementById("video-analysis")?.scrollIntoView({behavior:"smooth",block:"start"});}
  async function runDemo(demo){setSelectedDemo(demo);setError("");try{const response=await fetch(demo.file);if(!response.ok)throw new Error("Demo file could not be loaded.");const blob=await response.blob();setVideoFile(new File([blob],demo.filename,{type:"video/webm"}));document.getElementById("video-analysis")?.scrollIntoView({behavior:"smooth",block:"start"});}catch(err){setError(err.message);}}
  return <main className="console-shell"><div className="console-wrap">
    <header className="masthead"><div><p className="eyebrow">Visual safety prototype</p><h1 className="hero-title">Real-time video detection</h1><p className="hero-copy">Play a video and watch the model inspect frames continuously. The status changes as each new prediction arrives.</p></div><HealthBadge health={health} loading={healthLoading}/></header>
    <div className="warning-strip"><AlertCircle className="h-5 w-5 shrink-0"/><p>{DISCLAIMER}</p></div>
    <section className="how-it-works" aria-label="How detection works"><div><strong>1</strong><span><b>Play a video</b><small>Choose a sample or upload a file.</small></span></div><div><strong>2</strong><span><b>Frames are captured</b><small>The browser sends one current frame each second.</small></span></div><div><strong>3</strong><span><b>The status updates</b><small>The server model returns a class and confidence.</small></span></div></section>
    <section className="explanation panel"><div><p className="module-id">How it works</p><h2>Detection, in plain language</h2></div><div className="explanation-grid"><p><b>Frame capture</b><span>The video stays in your browser. While it plays, a still frame is captured approximately once per second.</span></p><p><b>Model inference</b><span>That frame is sent to the existing prediction API and resized into the format expected by the model.</span></p><p><b>Live warning</b><span>The newest class and confidence update the meter immediately. Network and server speed determine latency.</span></p></div></section>
    {error&&<div className="error-strip"><AlertCircle className="h-5 w-5 shrink-0"/><p>{error}</p></div>}
    <section className="metric-grid" aria-label="Analysis overview"><Metric label="Saved analyses" value={stats.total||0} icon={Database}/><Metric label="Image records" value={stats.by_kind?.image||0} icon={Image}/><Metric label="Video records" value={stats.by_kind?.video||0} icon={Video}/></section>
    <section className="panel"><div className="panel-head"><div><p className="module-id">Sample footage</p><h2>Choose a demonstration</h2><p className="muted mt-2 text-sm">Select a clip, then press play in the live monitor. Incident badges describe the source context; they are not model results.</p></div></div><div className="severity-guide"><span className="clear">Low</span><span className="warning">Review</span><span className="danger">Alert</span></div><div className="demo-grid">{DEMOS.map(demo=><article className="demo-card" key={demo.id}><div className="video-wrap"><video src={demo.file} muted playsInline preload="metadata" aria-label={`${demo.title} preview`}/><span className={`severity-badge ${demo.severity}`}>{demo.response}</span></div><div className="demo-copy"><h3>{demo.title}</h3><p className="muted">{demo.detail}</p><div className="demo-actions"><button className="action-button" onClick={()=>runDemo(demo)}>Use this video</button><a href={demo.source} target="_blank" rel="noreferrer">Source</a></div></div></article>)}</div><p className="demo-note">Real, non-graphic surveillance footage. Nothing autoplays. Pressing “Use this video” only loads it into the monitor.</p></section>
    <section className="grid-two"><UploadBox title="Evidence image input" description="Load one local frame to inspect anonymous class probabilities." accept="image/*" previewUrl={previewUrl} fileName={imageFile?.name} loading={loading} onFile={handleImage}/><ResultCard result={imageResult}/></section>
    <section className="grid-two live-section" id="video-analysis"><UploadBox title="Upload your video" description="Choose a local video. It will be analyzed only while you play it." accept="video/*" fileName={videoFile?.name} loading={false} onFile={handleVideo} mode="video"/>
      <RiskMonitor videoUrl={videoPreviewUrl} demo={selectedDemo}/>
    </section>
    <section className="panel"><div className="panel-head"><div><p className="module-id">Module 05 // Archive</p><h2>Recent Analyses</h2><p className="muted mt-2 text-sm">MongoDB stores metadata and outputs only. Uploaded media is discarded after processing.</p></div><button className="action-button" onClick={()=>refreshHistory().catch(err=>setError(err.message))}>Refresh feed</button></div>{analyses.length?<div className="data-table">{analyses.map(a=><div key={a.id} className="archive-row"><span className="archive-kind">{a.kind}</span><div className="truncate"><strong>{a.filename}</strong><div className="muted truncate">{a.predicted_class||`${a.sampled_frames||0} sampled frames`}</div></div><time className="muted" dateTime={a.created_at}>{new Date(a.created_at).toLocaleString()}</time></div>)}</div>:<p className="muted text-sm">No analyses saved. Load an image or video to initialize the feed.</p>}</section>
  </div></main>;
}
function Metric({label,value,icon:Icon}){return <div className="metric">{Icon&&<Icon className="metric-icon"/>}<p className="metric-label">{label}</p><p className="metric-value">{value}</p></div>}

const DEMO_RISK={class_0:18,class_1:58,class_2:92};
function RiskMonitor({videoUrl,demo}){
 const videoRef=useRef(null),canvasRef=useRef(null),busyRef=useRef(false),lastScanRef=useRef(-2);
 const [prediction,setPrediction]=useState(null),[scans,setScans]=useState(0),[latency,setLatency]=useState(null),[scanError,setScanError]=useState(""),[playing,setPlaying]=useState(false);
 useEffect(()=>{setPrediction(null);setScans(0);setLatency(null);setScanError("");lastScanRef.current=-2;},[videoUrl]);
 async function scanCurrentFrame(){const video=videoRef.current;if(!video||busyRef.current||video.paused||video.ended||video.currentTime-lastScanRef.current<1)return;if(!video.videoWidth)return;busyRef.current=true;lastScanRef.current=video.currentTime;const started=performance.now();try{const canvas=canvasRef.current;canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext("2d").drawImage(video,0,0);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/jpeg",.82));if(!blob)throw new Error("Could not capture this frame.");const result=await predictImage(new File([blob],`live-frame-${scans+1}.jpg`,{type:"image/jpeg"}));setPrediction({...result,time:video.currentTime});setScans(value=>value+1);setLatency(Math.round(performance.now()-started));setScanError("");}catch(err){setScanError(err.message);}finally{busyRef.current=false;}}
 const risk=prediction?DEMO_RISK[prediction.predicted_class]??Math.round(prediction.confidence*100):0;
 const level=risk>=75?"danger":risk>=40?"warning":"clear";
 return <section className={`panel risk-monitor ${level}`}><p className="module-id">Live monitor</p><h2>Frame-by-frame detection</h2>{videoUrl?<div className="mt-5">{demo&&<p className="annotation-note">Source context: <strong>{demo.detail}</strong></p>}<div className={`live-alert ${level}`}><ShieldAlert/><div><span>{!prediction?"Waiting for playback":level==="danger"?"Alert signal":level==="warning"?"Review signal":"Low signal"}</span><small>{playing?"Analyzing while video plays":"Paused"} · {scans} frames processed · {latency?`${latency} ms last response`:"no response yet"}</small></div><strong>{risk}%</strong></div><video ref={videoRef} className="monitor-video" src={videoUrl} controls playsInline onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onTimeUpdate={scanCurrentFrame}/><canvas ref={canvasRef} hidden/><div className="risk-track"><div className="risk-level" style={{width:`${risk}%`}}/></div><div className="risk-labels"><span>LOW</span><span>REVIEW</span><span>ALERT</span></div>{prediction&&<div className="live-facts"><span><small>Current frame</small>{prediction.time.toFixed(1)}s</span><span><small>Model class</small>{prediction.predicted_class}</span><span><small>Confidence</small>{Math.round(prediction.confidence*100)}%</span></div>}{scanError&&<p className="error-strip mt-4">{scanError}</p>}<p className="warning-strip mt-4">Risk is a prototype interpretation of anonymous classes: class_0 low, class_1 review, class_2 alert. Confirm the original label order before real-world use.</p></div>:<p className="muted mt-3 text-sm leading-6">Choose a sample or upload a video. Press play and this panel will process the current frame approximately once per second.</p>}</section>;
}
