import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BarChart3, Database, Image, RefreshCw, Video } from "lucide-react";
import { getAnalyses, getHealth, getStats, predictImage, predictVideo } from "./api.js";
import HealthBadge from "./components/HealthBadge.jsx";
import ResultCard from "./components/ResultCard.jsx";
import UploadBox from "./components/UploadBox.jsx";

const DISCLAIMER="Research prototype. The original label order is unavailable, so class outputs have no verified real-world meaning. Do not use results as evidence or for safety, law-enforcement, or emergency decisions.";
const DEMOS=[
 {id:"arrest",title:"Arrest sequence",quality:"Low · 160×120",file:"/research-demos/arrest-low-160x120.webm",filename:"Arrest002-low.webm",description:"Resolution stress test",annotation:"UCA annotation: a person runs over and subdues another person.",range:"4.1–15.0 seconds"},
 {id:"arson",title:"Arson precursor",quality:"Native · 320×240",file:"/research-demos/arson-native-320x240.webm",filename:"Arson003-native.webm",description:"Native source resolution",annotation:"UCA annotation: a person runs and pours gasoline on cabinets.",range:"0.1–17.5 seconds"},
 {id:"normal",title:"Normal traffic",quality:"Upscaled · 640×480",file:"/research-demos/normal-upscaled-640x480.webm",filename:"Normal050-upscaled.webm",description:"Upscale sensitivity test",annotation:"UCA annotation: ordinary road traffic with congestion in one lane.",range:"0.0–12.5 seconds"},
];

export default function App(){
 const [health,setHealth]=useState(null),[healthLoading,setHealthLoading]=useState(true),[imageFile,setImageFile]=useState(null),[imageResult,setImageResult]=useState(null),[videoFile,setVideoFile]=useState(null),[videoResult,setVideoResult]=useState(null),[activeDemo,setActiveDemo]=useState(null),[loading,setLoading]=useState(false),[videoLoading,setVideoLoading]=useState(false),[error,setError]=useState(""),[analyses,setAnalyses]=useState([]),[stats,setStats]=useState({total:0,by_kind:{}}),[sampleEvery,setSampleEvery]=useState(120);
 const previewUrl=useMemo(()=>imageFile?URL.createObjectURL(imageFile):"",[imageFile]);
 useEffect(()=>{getHealth().then(setHealth).catch(err=>setHealth({status:"error",message:err.message})).finally(()=>setHealthLoading(false));},[]);
 async function refreshHistory(){const [history,summary]=await Promise.all([getAnalyses(),getStats()]);setAnalyses(history.analyses||[]);setStats(summary);}
 useEffect(()=>{refreshHistory().catch(()=>null);},[]);
 useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl);},[previewUrl]);
 async function handleImage(file){setImageFile(file);setImageResult(null);setError("");setLoading(true);try{setImageResult(await predictImage(file));await refreshHistory().catch(()=>null);}catch(err){setError(err.message);}finally{setLoading(false);}}
 async function handleVideo(file,demo=null){setActiveDemo(demo);setVideoFile(file);setVideoResult(null);setError("");setVideoLoading(true);try{setVideoResult(await predictVideo(file,sampleEvery));await refreshHistory().catch(()=>null);document.getElementById("video-results")?.scrollIntoView({behavior:"smooth",block:"start"});}catch(err){setError(err.message);}finally{setVideoLoading(false);}}
 async function runDemo(demo){setError("");setVideoLoading(true);try{const response=await fetch(demo.file);if(!response.ok)throw new Error("Test video could not be loaded.");const blob=await response.blob();await handleVideo(new File([blob],demo.filename,{type:"video/webm"}),demo);}catch(err){setError(err.message);setVideoLoading(false);}}
 return <main className="app-shell"><div className="app-wrap">
  <header className="topbar"><div><p className="kicker">Visual classification research</p><h1>Video analysis workspace</h1><p>Test the original model against images, uploaded videos, and controlled research samples.</p></div><HealthBadge health={health} loading={healthLoading}/></header>
  <div className="notice"><AlertTriangle/><p>{DISCLAIMER}</p></div>
  {error&&<div className="error-notice"><AlertTriangle/><p>{error}</p></div>}
  <section className="metrics"><Metric label="Saved analyses" value={stats.total||0} icon={Database}/><Metric label="Images" value={stats.by_kind?.image||0} icon={Image}/><Metric label="Videos" value={stats.by_kind?.video||0} icon={Video}/></section>
  <section className="section-card"><SectionTitle eyebrow="Model evaluation" title="Resolution test videos" text="Each 20-second clip is sent unchanged through the original video prediction endpoint."/><div className="demo-grid">{DEMOS.map(demo=><article className="demo-card" key={demo.id}><video src={demo.file} controls muted playsInline preload="metadata"/><div><span>{demo.quality}</span><h3>{demo.title}</h3><p>{demo.annotation}</p><small>{demo.range} · {demo.description}</small><button disabled={videoLoading} onClick={()=>runDemo(demo)}>{videoLoading?"Testing…":"Run model test"}</button></div></article>)}</div><p className="footnote">All source clips are 320×240. The low and upscaled versions intentionally test resolution sensitivity; upscaling does not create additional detail. UCA descriptions are ground truth for comparison, not inputs to the model.</p></section>
  <section className="two-column"><UploadBox title="Image test" description="Upload one frame to inspect the model's anonymous class probabilities." accept="image/*" previewUrl={previewUrl} fileName={imageFile?.name} loading={loading} onFile={handleImage}/><ResultCard result={imageResult}/></section>
  <section className="two-column" id="video-results"><UploadBox title="Upload video" description="The backend samples frames and returns the original model output over time." accept="video/*" fileName={videoFile?.name} loading={videoLoading} onFile={file=>handleVideo(file)} mode="video"/><VideoResults result={videoResult} demo={activeDemo} sampleEvery={sampleEvery} onSampleEvery={setSampleEvery}/></section>
  <section className="section-card"><div className="section-head"><SectionTitle eyebrow="Stored metadata" title="Recent analyses" text="Uploaded media is discarded after processing; MongoDB stores outputs and metadata only."/><button className="secondary-button" onClick={()=>refreshHistory().catch(err=>setError(err.message))}><RefreshCw/>Refresh</button></div>{analyses.length?<div className="history">{analyses.map(item=><div key={item.id}><strong>{item.kind}</strong><span><b>{item.filename}</b><small>{item.predicted_class||`${item.sampled_frames||0} sampled frames`}</small></span><time dateTime={item.created_at}>{new Date(item.created_at).toLocaleString()}</time></div>)}</div>:<p className="empty-copy">No analyses saved yet.</p>}</section>
 </div></main>;
}

function VideoResults({result,demo,sampleEvery,onSampleEvery}){return <section className="section-card result-panel"><SectionTitle eyebrow="Original backend output" title="Video results" text="Frame predictions are shown exactly as returned by the existing API."/>{demo&&<div className="ground-truth"><strong>Research reference</strong><p>{demo.annotation}</p><span>{demo.range}</span></div>}{result?<><div className="result-metrics"><Metric label="Frames sampled" value={result.sampled_frames}/><Metric label="Classes returned" value={new Set(result.frame_predictions.map(frame=>frame.predicted_class)).size}/><Metric label="Average confidence" value={`${Math.round(result.average_confidence*100)}%`}/></div><div className="frame-table">{result.frame_predictions.map(frame=><div key={frame.frame_index}><time>{frame.timestamp_seconds}s</time><strong>{frame.predicted_class}</strong><span>{Math.round(frame.confidence*100)}%</span></div>)}</div></>:<div className="result-empty"><BarChart3/><p>Run a test video or upload your own footage to see results.</p></div>}<label className="range-label">Sample every {sampleEvery} frames<input type="range" min="5" max="120" step="5" value={sampleEvery} onChange={e=>onSampleEvery(Number(e.target.value))}/></label></section>}
function SectionTitle({eyebrow,title,text}){return <div className="section-title"><p>{eyebrow}</p><h2>{title}</h2><span>{text}</span></div>}
function Metric({label,value,icon:Icon}){return <div className="metric">{Icon&&<Icon/>}<span>{label}</span><strong>{value}</strong></div>}
